---
title: "horse_race"
output: html_document
date: "2025-10-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)
setwd("horse_race_functions")
# Load all function files automatically
source("csv_to_js.R")
source("export_last_race_csv.R")
source("generate_horse_names.R")
source("horse_add.R")
source("set_race_params.R")
source("normalize_horse_speeds.R")
source("update_positions_by_name.R")
source("html_difference.R")



```



```{r}


horses <- read.csv("horse.csv", row.names = 1)

csv_extra_js(csv_path = "horse.csv")

write.csv(horses, "horses.csv")

```





#GENERATE 99 horses

```{r}
# assume your original data frame is called df
# e.g. df <- read.csv("C:/Users/skacar/Documents/horse_race/horses.csv")
#sampeCOLORHORSES FOR ALL COLOR
#csv_to_js_grass(c(29, 1, 9, 4,
                  #34, 7,12, 16,
                  #3, 5,
                  #14,46,42,
                  #31, 10, 13, 2))

horses$hndp_race <- ifelse(horses$handicap == 0, 0, 1)

hanzero <- rownames(horses)[horses$handicap == 0]

first <- hanzero[1:15]
sec <- hanzero[16:31]
third <- hanzero[31:44]

csv_to_js_grass_position(first)
csv_to_js_grass_position(sec)
csv_to_js_grass_position(third)


part <- rownames(parts[[9]])

csv_to_js_grass_position(c(62:79))
csv_to_js_dirt(c(80:98))

set_race_params(ww = 15000, fl = 14500, ch = 5000, cw = 2500, strategy = "assignRacingStrategies_sedat", html_name = "deneme_control_canvas25") #2


export_last_race_csv_try()







write.csv(horses, "horses1.csv")

horse_add(overwrite = T)

html_difference(first_html = "deneme_control_canvas19", second_html = "deneme_control_canvas21" , directory = "C:/Users/skacar/Documents/horse_race/")



```

#11 groups

```{r}
horse1 <- horses[order(-horses$handicap), ]

n_parts <- 9
n <- nrow(horse1)

# Generate group labels
groups <- gl(n_parts, ceiling(n / n_parts), n)

# Split into 9 data frames
parts <- split(horse1, groups)

part <- rownames(parts[[1]])
csv_to_js_grass_position(part)

set_race_params(ww = 20500, fl =19000, ch = 4000, cw = 1800, strategy = "assignRacingStrategies_sedat", html_name = "deneme_control_canvas26") #2

export_last_race_csv_try()


```




```{r}
race_last <- read.csv("race_last.csv")
race_last$handicap


ww = 5000
fl = 4500
cw = 1200
ch = 600
lg = 10
lo = 100


  backgroundTop <- "#D2B48C"
  backgroundBottom <-  "#C19A6B"
  border <-  "#8B4513"



  # Write simple JS file
  js_config <- sprintf(
    "window.TRACK_STYLE = {backgroundTop:%s, backgroundBottom:%s, border:%s};",
    backgroundTop, backgroundBottom, border)
  
  writeLines(js_config, "C:/Users/skacar/Documents/horse_race/race_params.js")
  
  ?writeLines
  
```



